image: ruby:2.3 

variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  JEKYLL_ENV: production

pages:
  script:
    - bundle install
    - mkdir public/test
    - cp public/classes/exercices/*.md public/test/
    - bundle exec jekyll build -d public/test_deploy -s public/test --config public/classes/exercices/_config.yml
  stage: deploy
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  artifacts:
    paths:
    - public
  only:
  - master
