image: node:4.2.2 

pages:
  cache:
    paths:
    - node_modules/

  script:
    - mkdir public
    - cp -r docs/* public
    - npm install metalsmith
    - cp -r docs/classes/exercises/*.md metalsmith_pages/src/
    - cd metalsmith_pages && make build
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  after_script:
          #- sed -i "1 i---\n\nlayout:page.html\n\n---\n\n" public/classes/exercises/*.md
          #- sed -i "s/page.html/ page.html/" public/classes/exercises/*.md
    - for i in $(ls metalsite |grep "ex"); do mv metalsite/${i}/index.html public/classes/exercises/${i}.html; done
    - mv metalsite/styles public/classes/exercises/styles
    - mv metalsmith_pages/src/images public/classes/exercises/images
  artifacts:
    paths:
    - public
  only:
  - master
