image: node:4.2.2 

pages:
  cache:
    paths:
    - node_modules/

  script:
    - npm install metalsmith
    - cd public/classes/exercices && make build
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  artifacts:
    paths:
    - public
  only:
  - master
