image: node:4.2.2 

pages:
  cache:
    paths:
    - node_modules/

  script:
    - mkdir public
    - cp -r docs/* public
    - npm install metalsmith
    - cp -r docs/classes/exercices/*.md metalsmith_pages/src/
    - cd metalsmith_pages && make build
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  artifacts:
    paths:
    - public
  only:
  - master
