image: ruby:2.3 

variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  JEKYLL_ENV: production

pages:
  script:
    - bundle install
    - bundle exec jekyll build -d public/classes/exercices -s public/classes/exercices
  stage: deploy
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  artifacts:
    paths:
    - public/classes/exercices
  only:
  - master
