image: node:4.2.2 

pages:
  cache:
    paths:
    - node_modules/

  script:
    - npm install metalsmith
    - cd docs/classes/exercices && make build
    - cp -r docs/* public
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  artifacts:
    paths:
    - public
  only:
  - master
